export const config = {
    backgroundImages: [
        "/background_img/1.jpg",
        "/background_img/2.jpg",
        "/background_img/3.jpg",
        "/background_img/4.jpg",
        "/background_img/5.jpg",
        "/background_img/6.jpg",
        "/background_img/7.jpg",
        "/background_img/8.jpg",
        "/background_img/9.jpg",
        "/background_img/10.jpg",
        "/background_img/11.jpg",
        "/background_img/12.jpg",
        "/background_img/13.jpg",
        "/background_img/14.jpg",
        "/background_img/15.jpg",
        "/background_img/16.jpg",
        "/background_img/17.jpg",
        "/background_img/18.jpg",
        "/background_img/19.jpg",
        "/background_img/20.jpg",
    ],
    backgroundChangeTime: 6000,
}